version: "3.7"

services:
  mysqldb:
    image: mysql:5.7
    restart: always
    secrets:
      - db_password
      - db_root_password
    networks:
      - webnet
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
      MYSQL_DATABASE: Project
      MYSQL_USER: Melih
  wordpress:
    image: wordpress:latest
    depends_on:
      - mysqldb
    restart: always
    secrets:
      - db_password
    networks:
      - webnet
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_PASSWORD_FILE: /run/secrets/db_password
      WORDPRESS_DB_USER: Melih
      WORDPRESS_DB_HOST: mysqldb
      WORDPRESS_DB_NAME: Project
networks:
  webnet:
    driver: overlay
secrets:
  db_password:
    file: secrets/db_password.txt
  db_root_password:
    file: secrets/db_root_password.txt
